CREATE TABLE POLICY (
    POLICY_ID NUMBER PRIMARY KEY,
    POLICY_NUMBER VARCHAR2(50) NOT NULL,
    POLICY_STATUS VARCHAR2(20) NOT NULL,
    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

ALTER TABLE POLICY ADD CONSTRAINT CHK_POLICY_STATUS
    CHECK (POLICY_STATUS IN ('ACTIVE','INACTIVE','EXPIRED','CANCELLED'));

CREATE SEQUENCE POLICY_SEQ START WITH 1;