CREATE TABLE CLAIM (
   CLAIM_ID NUMBER PRIMARY KEY,
   CLAIM_NUMBER VARCHAR2(30) UNIQUE,
   POLICY_ID NUMBER NOT NULL,
   CLAIM_DATE DATE,
   CLAIM_AMOUNT NUMBER(15,2),
   APPROVED_AMOUNT NUMBER(15,2),
   CLAIM_STATUS VARCHAR2(20),
   CLAIM_TYPE VARCHAR2(20),
   DESCRIPTION VARCHAR2(500),
   CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
   VERSION_NO NUMBER
);

ALTER TABLE CLAIM
ADD CONSTRAINT FK_CLAIM_POLICY
FOREIGN KEY (POLICY_ID)
REFERENCES POLICY(POLICY_ID);

CREATE SEQUENCE CLAIM_SEQ START WITH 1;