CREATE TABLE CLAIM_STATUS_HISTORY (
  HISTORY_ID NUMBER PRIMARY KEY,
  CLAIM_ID NUMBER,
  OLD_STATUS VARCHAR2(20),
  NEW_STATUS VARCHAR2(20),
  NOTE VARCHAR2(500),
  CHANGED_AT TIMESTAMP
);

CREATE SEQUENCE CLAIM_HISTORY_SEQ;
